### ISSUE TITLE
The downloaded PDF doesn't contain anything!

### ISSUE THREAD

**Issue by sanjai0py** [anandbaburajan/wordamour#1]
https://github.com/user-attachments/assets/e9ed4eeb-d32f-441b-bb9b-9d4bd108a949

**Comment by anandbaburajan** [comment]
Hi @sanjai0py, thanks for reporting! Are you using the Brave browser? I've tried it on Chrome and Firefox, and it works there. I'll try it out on Brave, but I wanted to know if you might be using any extensions which are interfering with the app?

**Comment by anandbaburajan** [comment]
Edit: your browser doesn't seem to be Brave. And, I just tried on Brave, and it works there too. Which browser are you using?

**Comment by sanjai0py** [comment]
Microsoft Edge
Version 131.0.2903.51 (Official build) (arm64)

**Comment by sanjai0py** [comment]
Ok, it’s something caused by the extensions I have. I tried opening in private mode with all the extensions disabled; now it works just fine.
